In [2]:
import pandas as pd
finance = pd.read_csv("C:/UBCO/DATA_301/project-group44-project-1/data/processed/Data.csv")
finance

,Date,Unnamed: 1,Bank rate,Chartered bank administered interest rates - Prime rate 1,Chartered bank - consumer loan rate 1,"Forward premium or discount (-), United States dollars in Canada: 1 month (Terminated)","Forward premium or discount (-), United States dollars in Canada: 3 month (Terminated)",Prime corporate paper rate: 1 month (Terminated) 2 3,Prime corporate paper rate: 2 month (Terminated) 2 3,Prime corporate paper rate: 3 month (Terminated) 2 3,...,Chartered bank - Guaranteed Investment Certificates: 3 year 1,Chartered bank - Guaranteed Investment Certificates: 5 year 1,Treasury Bills: 1 month,Treasury Bills: 2 month,Treasury Bills: 3 month,Treasury Bills: 6 month,Treasury Bills: 1 year,"Real return bonds, long-term",Contractual interest rate for new insured 5-year fixed rate mortgages,Benchmark qualifying mortgage rate 1
0,3-Jan-18,NaN,1.25,3.20,9.0,..t,..t,1.39t,1.42t,1.49t,...,1.35,1.6,0.95,1.01,1.06,1.21,1.52,0.58,..,..
1,10-Jan-18,NaN,1.25,3.20,9.0,..t,..t,1.46t,1.51t,1.56t,...,1.35,1.6,0.94,1.04,1.17,1.38,1.62,0.63,..,..
2,17-Jan-18,NaN,1.50,3.20,9.0,..t,..t,1.47t,1.52t,1.57t,...,1.35,1.6,1.00,1.13,1.18,1.35,1.60,0.59,..,..
3,24-Jan-18,NaN,1.50,3.45,9.0,..t,..t,1.47t,1.52t,1.57t,...,1.35,1.6,1.11,1.13,1.21,1.36,1.62,0.60,..,..
4,31-Jan-18,NaN,1.50,3.45,9.0,..t,..t,1.47t,1.53t,1.57t,...,1.35,1.6,1.12,1.15,1.20,1.34,1.61,0.60,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,25-Aug-21,NaN,0.50,2.45,7.7,..t,..t,..t,..t,..t,...,0.60,1.0,0.19,0.21,0.18,0.17,0.27,0.15,..,..
191,1-Sep-21,NaN,0.50,2.45,7.7,..t,..t,..t,..t,..t,...,0.60,1.0,0.19,0.15,0.12,0.18,0.25,0.06,..,..
192,8-Sep-21,NaN,0.50,2.45,7.7,..t,..t,..t,..t,..t,...,0.60,1.0,0.19,0.14,0.15,0.17,0.27,0.04,..,..
193,15-Sep-21,NaN,0.50,2.45,7.7,..t,..t,..t,..t,..t,...,0.60,1.0,0.19,0.13,0.15,0.18,0.28,0.03,..,..
194,22-Sep-21,NaN,0.50,2.45,7.7,..t,..t,..t,..t,..t,...,0.60,1.0,0.20,0.11,0.12,0.15,0.26,0.05,..,..

In [2]:
import numpy as np
df = finance
df[df ==".."] = np.nan
df[df =="..t"] = np.nan
df_cleaned = df.dropna(axis=0)
df_cleaned = df_cleaned.T
df_cleaned

Empty DataFrame
Columns: []
Index: [Date, Unnamed: 1, Bank rate, Chartered bank administered interest rates - Prime rate 1, Chartered bank - consumer loan rate 1, Forward premium or discount (-), United States dollars in Canada: 1 month (Terminated), Forward premium or discount (-), United States dollars in Canada: 3 month (Terminated), Prime corporate paper rate: 1 month (Terminated) 2 3, Prime corporate paper rate: 2 month (Terminated) 2 3, Prime corporate paper rate: 3 month (Terminated) 2 3, Bankers' acceptances: 1 month (Terminated) 3 4, Bankers' acceptances: 2 month (Terminated) 3 4, Bankers' acceptances: 3 month (Terminated) 3 4, Overnight money market financing, 7 day average 5, Selected Government of Canada benchmark bond yields: 2 year, Selected Government of Canada benchmark bond yields: 3 year, Selected Government of Canada benchmark bond yields: 5 year, Selected Government of Canada benchmark bond yields: 7 year, Selected Government of Canada benchmark bond yields: 10 year, Selected Government of Canada benchmark bond yields: long term, Government of Canada marketable bonds, average yield: 1-3 year 6, Government of Canada marketable bonds, average yield: 3-5 year 6, Government of Canada marketable bonds, average yield: 5-10 year 6, Government of Canada marketable bonds, average yield: over 10 years 6, Chartered banks - 90 day term deposits 1, Chartered bank - conventional mortgage: 1 year 1, Chartered bank - conventional mortgage: 3 year 1, Chartered bank - conventional mortgage: 5 year, Chartered bank - 5 year personal fixed term 1, Chartered bank - daily interest savings (balance over $100,000) 1, Chartered bank - non-chequable savings deposit 1, Chartered bank - Guaranteed Investment Certificates: 1 year 1, Chartered bank - Guaranteed Investment Certificates: 3 year 1, Chartered bank - Guaranteed Investment Certificates: 5 year 1, Treasury Bills: 1 month, Treasury Bills: 2 month, Treasury Bills: 3 month, Treasury Bills: 6 month, Treasury Bills: 1 year, Real return bonds, long-term, Contractual interest rate for new insured 5-year fixed rate mortgages, Benchmark qualifying mortgage rate 1, Unnamed: 42, Unnamed: 43, Unnamed: 44, Unnamed: 45, Unnamed: 46, Unnamed: 47, Unnamed: 48, Unnamed: 49, Unnamed: 50, Unnamed: 51, Unnamed: 52, Unnamed: 53, Unnamed: 54, Unnamed: 55, Unnamed: 56, Unnamed: 57, Unnamed: 58, Unnamed: 59, Unnamed: 60, Unnamed: 61, Unnamed: 62, Unnamed: 63, Unnamed: 64, Unnamed: 65, Unnamed: 66, Unnamed: 67, Unnamed: 68, Unnamed: 69, Unnamed: 70, Unnamed: 71, Unnamed: 72, Unnamed: 73, Unnamed: 74, Unnamed: 75, Unnamed: 76, Unnamed: 77, Unnamed: 78, Unnamed: 79, Unnamed: 80, Unnamed: 81, Unnamed: 82, Unnamed: 83, Unnamed: 84, Unnamed: 85, Unnamed: 86, Unnamed: 87, Unnamed: 88, Unnamed: 89, Unnamed: 90, Unnamed: 91, Unnamed: 92, Unnamed: 93, Unnamed: 94, Unnamed: 95, Unnamed: 96, Unnamed: 97, Unnamed: 98, Unnamed: 99, ...]

[196 rows x 0 columns]

In [8]:
import project_functions1 as p1
df1 = p1.load_and_process("C:/UBCO/DATA_301/project-group44-project-1/data/processed/Data.csv")
df1
df1.plot("Date","Bank rate")
df1.plot("Date","Chartered bank administered interest rates - Prime rate 1")
df1.plot("Date","Selected Government of Canada benchmark bond yields: 2 year")
df1.plot("Date","Government of Canada marketable bonds, average yield: 1-3 year 6")
df1.plot("Date","Chartered banks - 90 day term deposits 1")
df1.plot("Date","Treasury Bills: 1 month")
df1.plot("Date","Real return bonds, long-term")

ImportError: attempted relative import with no known parent package

In [4]:
df = pd.read_csv("../../data/processed/Data.csv")

In [5]:
import project_functions1 as p1
df1 = p1.load_and_process("../data/processed/Data.csv")
df1

ModuleNotFoundError: No module named 'project_functions1'